version: "3"
services:
  ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
  dapp:
    build: .
    ports: 
      - "4000:4000"
    depends_on:
      - ganache
    
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "8081:8081"
    depends_on:
      - dapp