# base image - node:alpine
FROM node:alpine

# Import SSH key
ARG src="//mnt/c/Users/ageki/Mes documents/Project/ssh/.ssh"
RUN mkdir ~/.ssh
COPY ${src} ~/.ssh/

# set the working directory to /app
WORKDIR /app

# install ganache-cli globally
RUN npm install -g ganache-cli

# set the command ganache-cli -h 0.0.0.0 
# for docker ganache-cli host on 0.0.0.0
CMD ["ganache-cli","-h","0.0.0.0"]